;this file for FamiTone2 library generated by text2data tool

weAreNumber2_2_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $30 ;instrument $00
	.dw .env1,.env3,.env4
	.db $00
	.db $70 ;instrument $01
	.dw .env1,.env0,.env5
	.db $00
	.db $b0 ;instrument $02
	.dw .env2,.env0,.env6
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $cb,$cd,$ce,$cf,$05,$ce,$cd,$cd,$cc,$cc,$cb,$ca,$c8,$c7,$c6,$c5
	.db $c3,$c1,$00,$11
.env2:
	.db $c1,$c2,$c3,$c4,$c5,$c6,$00,$05
.env3:
	.db $c0,$02,$c5,$02,$cc,$02,$b9,$b9,$b9,$00,$00
.env4:
	.db $c1,$c1,$c0,$c0,$c0,$00,$00
.env5:
	.db $e1,$ff,$ff,$00,$02
.env6:
	.db $c0,$24,$c5,$c8,$ca,$c8,$c5,$c0,$bb,$b8,$b6,$b8,$bb,$c0,$00,$02


.song0ch0:
	.db $fb,$06
.song0ch0loop:
.ref0:
	.db $f9,$85
.ref1:
	.db $f9,$85
.ref2:
	.db $f9,$85
.ref3:
	.db $f9,$85
.ref4:
	.db $f9,$85
.ref5:
	.db $f9,$85
.ref6:
	.db $f9,$85
.ref7:
	.db $f9,$85
.ref8:
	.db $84,$1e,$8d,$25,$1f,$24,$95,$22,$8d,$1a,$8d,$22,$8d,$1e,$95,$00
	.db $85
.ref9:
	.db $1e,$8d,$25,$1f,$24,$95,$22,$8d,$1a,$8d,$22,$8d,$2c,$95,$00,$85
.ref10:
	.db $2c,$8d,$29,$25,$2c,$9d,$2c,$85,$24,$8d,$28,$8d,$2c,$95,$00,$85
	.db $ff,$10
	.dw .ref10
.ref12:
	.db $2c,$8d,$29,$25,$2c,$9d,$2c,$85,$24,$8d,$28,$8d,$1e,$95,$00,$85
	.db $ff,$10
	.dw .ref10
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref14:
	.db $80,$2c,$bd,$24,$8d,$28,$8d,$2c,$9d
.ref15:
	.db $2c,$bd,$24,$8d,$28,$8d,$2c,$9d
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
.ref20:
	.db $2c,$9d,$24,$9d,$28,$8d,$24,$8d,$1e,$9d
	.db $ff,$0a
	.dw .ref20
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
	.db $ff,$0a
	.dw .ref20
	.db $ff,$0a
	.dw .ref20
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref28:
	.db $82,$24,$9d,$25,$24,$99,$1b,$1a,$89,$21,$20,$89,$25,$24,$99
.ref29:
	.db $24,$9d,$25,$24,$99,$1b,$1a,$89,$21,$20,$89,$25,$24,$99
.ref30:
	.db $24,$89,$37,$33,$37,$33,$37,$24,$89,$37,$33,$37,$33,$37,$1b,$1a
	.db $85,$2d,$21,$20,$85,$31,$25,$24,$85,$37,$33,$37,$33,$36,$81
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$0e
	.dw .ref29
	.db $ff,$0e
	.dw .ref29
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref42:
	.db $f9,$85
.ref43:
	.db $82,$02,$9d,$02,$9d,$02,$9d,$02,$9d
.ref44:
	.db $02,$9d,$02,$9d,$02,$9d,$02,$9d
.ref45:
	.db $02,$9d,$02,$9d,$02,$9d,$02,$91,$07,$07,$06,$81
.ref46:
	.db $02,$85,$06,$89,$03,$06,$85,$02,$85,$06,$89,$03,$06,$85,$02,$85
	.db $06,$89,$03,$06,$85,$02,$85,$06,$89,$03,$07,$06,$81
	.db $ff,$1d
	.dw .ref46
	.db $ff,$1d
	.dw .ref46
	.db $ff,$1d
	.dw .ref46
	.db $ff,$08
	.dw .ref44
	.db $ff,$0c
	.dw .ref45
	.db $ff,$1d
	.dw .ref46
	.db $ff,$1d
	.dw .ref46
	.db $ff,$1d
	.dw .ref46
	.db $ff,$0c
	.dw .ref45
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref56:
	.db $f9,$85
.ref57:
	.db $f9,$85
.ref58:
	.db $f9,$85
.ref59:
	.db $f9,$85
.ref60:
	.db $f9,$85
.ref61:
	.db $f9,$85
.ref62:
	.db $f9,$85
.ref63:
	.db $f9,$85
.ref64:
	.db $f9,$85
.ref65:
	.db $f9,$85
.ref66:
	.db $f9,$85
.ref67:
	.db $f9,$85
.ref68:
	.db $f9,$85
.ref69:
	.db $f9,$85
	.db $fd
	.dw .song0ch4loop
