;this file for FamiTone2 library generated by text2data tool

weAreNumber2_3_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $70 ;instrument $00
	.dw .env1,.env0,.env6
	.db $00
	.db $30 ;instrument $01
	.dw .env2,.env0,.env0
	.db $00
	.db $b0 ;instrument $02
	.dw .env3,.env0,.env7
	.db $00
	.db $30 ;instrument $04
	.dw .env4,.env5,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $c5,$c6,$c7,$05,$c6,$0b,$c5,$0f,$c4,$11,$c3,$14,$c2,$15,$c1,$1d
	.db $c0,$00,$10
.env2:
	.db $cf,$00,$00
.env3:
	.db $c1,$c2,$c3,$c4,$c5,$c6,$00,$05
.env4:
	.db $cf,$02,$ce,$cd,$cb,$c8,$c5,$c3,$c1,$02,$c0,$00,$0a
.env5:
	.db $c0,$c8,$00,$01
.env6:
	.db $c0,$0f,$c1,$c1,$c2,$c2,$c1,$c1,$c0,$c0,$00,$02
.env7:
	.db $c0,$24,$c5,$c8,$ca,$c8,$c5,$c0,$bb,$b8,$b6,$b8,$bb,$c0,$00,$02


.song0ch0:
	.db $fb,$04
.song0ch0loop:
.ref0:
	.db $f9,$85
.ref1:
	.db $f9,$85
.ref2:
	.db $f9,$85
.ref3:
	.db $f9,$85
.ref4:
	.db $f9,$85
.ref5:
	.db $f9,$85
.ref6:
	.db $f9,$85
.ref7:
	.db $f9,$85
.ref8:
	.db $84,$1e,$8d,$25,$1f,$24,$95,$22,$8d,$1a,$8d,$22,$8d,$1e,$95,$00
	.db $85
.ref9:
	.db $1e,$8d,$25,$1f,$24,$95,$22,$8d,$1a,$8d,$22,$8d,$2c,$95,$00,$85
.ref10:
	.db $2c,$8d,$29,$25,$2c,$9d,$2c,$85,$24,$8d,$28,$8d,$2c,$95,$00,$85
	.db $ff,$10
	.dw .ref10
.ref12:
	.db $2c,$8d,$29,$25,$2c,$9d,$2c,$85,$24,$8d,$28,$8d,$1e,$95,$00,$85
	.db $ff,$10
	.dw .ref10
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref14:
	.db $80,$2c,$bd,$24,$8d,$28,$8d,$2c,$9d
.ref15:
	.db $2c,$bd,$24,$8d,$28,$8d,$2c,$9d
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
.ref20:
	.db $2c,$9d,$24,$9d,$28,$8d,$24,$8d,$1e,$9d
	.db $ff,$0a
	.dw .ref20
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
	.db $ff,$08
	.dw .ref15
	.db $ff,$0a
	.dw .ref20
	.db $ff,$0a
	.dw .ref20
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref28:
	.db $82,$24,$9d,$25,$24,$99,$1d,$1c,$89,$21,$20,$89,$25,$24,$99
.ref29:
	.db $24,$9d,$25,$24,$99,$1d,$1c,$89,$21,$20,$89,$25,$24,$99
.ref30:
	.db $24,$89,$2f,$2b,$2f,$2b,$2f,$24,$89,$2f,$2b,$2f,$2b,$2f,$1d,$1c
	.db $85,$1d,$21,$20,$85,$21,$25,$24,$85,$2f,$2b,$2f,$2b,$2e,$81
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$0e
	.dw .ref29
	.db $ff,$0e
	.dw .ref29
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $ff,$1f
	.dw .ref30
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref42:
	.db $f9,$85
.ref43:
	.db $86,$14,$9d,$14,$9d,$14,$9d,$14,$9d
.ref44:
	.db $14,$9d,$14,$9d,$14,$9d,$14,$9d
.ref45:
	.db $14,$9d,$14,$9d,$14,$9d,$14,$91,$05,$05,$04,$81
.ref46:
	.db $14,$85,$04,$89,$15,$04,$85,$14,$85,$04,$89,$15,$04,$85,$14,$85
	.db $04,$89,$15,$04,$85,$14,$85,$04,$89,$15,$05,$04,$81
	.db $ff,$1d
	.dw .ref46
	.db $ff,$1d
	.dw .ref46
	.db $ff,$1d
	.dw .ref46
	.db $ff,$08
	.dw .ref44
	.db $ff,$0c
	.dw .ref45
	.db $ff,$1d
	.dw .ref46
	.db $ff,$1d
	.dw .ref46
	.db $ff,$1d
	.dw .ref46
	.db $ff,$0c
	.dw .ref45
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref56:
	.db $f9,$85
.ref57:
	.db $f9,$85
.ref58:
	.db $f9,$85
.ref59:
	.db $f9,$85
.ref60:
	.db $f9,$85
.ref61:
	.db $f9,$85
.ref62:
	.db $f9,$85
.ref63:
	.db $f9,$85
.ref64:
	.db $f9,$85
.ref65:
	.db $f9,$85
.ref66:
	.db $f9,$85
.ref67:
	.db $f9,$85
.ref68:
	.db $f9,$85
.ref69:
	.db $f9,$85
	.db $fd
	.dw .song0ch4loop
